// VarioSettings.h
//

#ifndef __VARIOSETTINGS_H__
#define __VARIOSETTINGS_H__


/////////////////////////////////////////////////////////////////////////////
//

// command code
#define CMD_STATUS				'ST'
#define CMD_RESET				'RS'
#define CMD_SHUTDOWN			'SD'
#define CMD_FIRMWARE_VERSION	'FV'
#define CMD_MODE_SWITCH			'MS'
#define CMD_SOUND_LEVEL			'SL'
#define CMD_TONE_TEST			'TT'
#define CMD_DUMP_SENSOR			'DS'
#define CMD_DUMP_PARAMETERS		'DP'
#define CMD_BLOCK_GPS_NMEA		'BG'
#define CMD_BLOCK_VARIO_NMEA	'BV'
#define CMD_FACTORY_RESET		'FR'
#define CMD_RESTORE_PARAM		'RP'
#define CMD_SAVE_PARAM			'SP'
#define CMD_QUERY_PARAM			'QP'
#define CMD_UPDATE_PARAM		'UP'

// response code
#define RCODE_RESULT			'RS'
#define RCODE_OK				'OK'
#define RCODE_FAIL				'FA'
#define RCODE_ERROR				'ER'
#define RCODE_NOT_READY			'NR'
#define RCODE_UNAVAILABLE		'UA'
#define RCODE_DUMP_PARAM		'DP'
#define RCODE_QUERY_PARAM		'QP'
#define RCODE_UPDATE_PARAM		'UP'


// mode switch
#define PARAM_SW_ICALIBRATION	(1)		// interactive
#define PARAM_SW_CALIBRATION	(2)		// no-interactive
#define PARAM_SW_UMS			(3)
#define PARAM_SW_CONFIG			(4)

// device status
#define PARAM_DS_ALL			(0)
#define PARAM_DS_IMU			(1)
#define PARAM_DS_SDCARD			(2)
#define PARAM_DS_GPS			(3)
#define PARAM_DS_VOLTAGE		(4)

// sensor dump
#define PARAM_DU_NONE			(0)
#define PARAM_DU_ACCELEROMETER	(1<<0)
#define PARAM_DU_GYROSCOPE		(1<<1)
#define PARAM_DU_PRESSURE		(1<<2)
#define PARAM_DU_TEMPERATURE	(1<<3)
#define PARAM_DU_ALL			(0x0F)

// nmea sentence
#define PARAM_NM_UNBLOCK		(0)
#define PARAM_NM_BLOCK			(1)

//  tone test
#define PARAM_TT_STOP			(0)
#define PARAM_TT_START			(1)

// sound level
#define PARAM_LV_MUTE			(0)
#define PARAM_LV_MEDIUM			(1)
#define PARAM_LV_LOUD			(2)

// device reset
#define PARAM_RS_NOW			(0)
#define PARAM_RS_AFTER_SAVE		(1)

#define MAX_PROFILE_SIZE		(16)
#define MAX_STRING_SIZE			(16)
#define TONE_TABLE_COUNT		(12)


enum GliderType
{
	GTYPE_UNKNOWNM,
	GTYPE_PARAGLIDER,
	GTYPE_HG_FLEX,
	GTYPE_HG_RIGID,
	GTYPE_SAILPLANE,
	GTYPE_PPG_FOOT,
	GTYPE_PPG_WHEEL
};

enum VarioSentence
{
	VSENTENCE_LK8,
	VSENTENCE_LXNAV,
};

enum PARAM_VarType
{
	PARAM_INT8_T,
	PARAM_INT16_T,
	PARAM_INT32_T,
	PARAM_UINT8_T,
	PARAM_UINT16_T,
	PARAM_UINT32_T,
	PARAM_FLOAT,
	PARAM_STRING
};

enum PARAM_Id
{
	// GliderInfo
	PARAM_GLIDER_TYPE					= 0x1001,
	PARAM_GLIDER_MANUFACTURE			= 0x1002,
	PARAM_GLIDER_MODEL					= 0x1003,
	// IGCLogger
	PARAM_LOGGER_ENABLE					= 0x1101,
	PARAM_LOGGER_TAKEOFF_SPEED			= 0x1102,
	PARAM_LOGGER_LANDING_TIMEOUT		= 0x1103,
	PARAM_LOGGER_LOGGING_INTERVAL		= 0x1104,
	PARAM_LOGGER_PILOT					= 0x1105,
	PARAM_LOGGER_TIMEZONE				= 0x1106,
	// VarioSettings
	PARAM_VARIO_SINK_THRESHOLD			= 0x1201,
	PARAM_VARIO_CLIMB_THRESHOLD			= 0x1202,
	PARAM_VARIO_SENSITIVITY				= 0x1203,
	PARAM_VARIO_SENTENCE				= 0x1204,
	PARAM_VARIO_BAROONLY				= 0x1205,
	// ToneTables 
	PARAM_TONETABLE_00_VELOCITY			= 0x1301,
	PARAM_TONETABLE_00_FREQ				= 0x1302,
	PARAM_TONETABLE_00_PERIOD			= 0x1303,
	PARAM_TONETABLE_00_DUTY				= 0x1304,
	PARAM_TONETABLE_01_VELOCITY			= 0x1311,
	PARAM_TONETABLE_01_FREQ				= 0x1312,
	PARAM_TONETABLE_01_PERIOD			= 0x1313,
	PARAM_TONETABLE_01_DUTY				= 0x1314,
	PARAM_TONETABLE_02_VELOCITY			= 0x1321,
	PARAM_TONETABLE_02_FREQ				= 0x1322,
	PARAM_TONETABLE_02_PERIOD			= 0x1323,
	PARAM_TONETABLE_02_DUTY				= 0x1324,
	PARAM_TONETABLE_03_VELOCITY			= 0x1331,
	PARAM_TONETABLE_03_FREQ				= 0x1332,
	PARAM_TONETABLE_03_PERIOD			= 0x1333,
	PARAM_TONETABLE_03_DUTY				= 0x1334,
	PARAM_TONETABLE_04_VELOCITY			= 0x1341,
	PARAM_TONETABLE_04_FREQ				= 0x1342,
	PARAM_TONETABLE_04_PERIOD			= 0x1343,
	PARAM_TONETABLE_04_DUTY				= 0x1344,
	PARAM_TONETABLE_05_VELOCITY			= 0x1351,
	PARAM_TONETABLE_05_FREQ				= 0x1352,
	PARAM_TONETABLE_05_PERIOD			= 0x1353,
	PARAM_TONETABLE_05_DUTY				= 0x1354,
	PARAM_TONETABLE_06_VELOCITY			= 0x1361,
	PARAM_TONETABLE_06_FREQ				= 0x1362,
	PARAM_TONETABLE_06_PERIOD			= 0x1363,
	PARAM_TONETABLE_06_DUTY				= 0x1364,
	PARAM_TONETABLE_07_VELOCITY			= 0x1371,
	PARAM_TONETABLE_07_FREQ				= 0x1372,
	PARAM_TONETABLE_07_PERIOD			= 0x1373,
	PARAM_TONETABLE_07_DUTY				= 0x1374,
	PARAM_TONETABLE_08_VELOCITY			= 0x1381,
	PARAM_TONETABLE_08_FREQ				= 0x1382,
	PARAM_TONETABLE_08_PERIOD			= 0x1383,
	PARAM_TONETABLE_08_DUTY				= 0x1384,
	PARAM_TONETABLE_09_VELOCITY			= 0x1391,
	PARAM_TONETABLE_09_FREQ				= 0x1392,
	PARAM_TONETABLE_09_PERIOD			= 0x1393,
	PARAM_TONETABLE_09_DUTY				= 0x1394,
	PARAM_TONETABLE_10_VELOCITY			= 0x13A1,
	PARAM_TONETABLE_10_FREQ				= 0x13A2,
	PARAM_TONETABLE_10_PERIOD			= 0x13A3,
	PARAM_TONETABLE_10_DUTY				= 0x13A4,
	PARAM_TONETABLE_11_VELOCITY			= 0x13B1,
	PARAM_TONETABLE_11_FREQ				= 0x13B2,
	PARAM_TONETABLE_11_PERIOD			= 0x13B3,
	PARAM_TONETABLE_11_DUTY				= 0x13B4,
	// VolumeSettings
	PARAM_VOLUME_VARIO					= 0x1401,
	PARAM_VOLUME_EFFECT					= 0x1402,
	// ThresholdSettings
	PARAM_THRESHOLD_LOW_BATTERY			= 0x1501,
	PARAM_THRESHOLD_SHUTDOWN_HOLDTIME	= 0x1502,
	PARAM_THRESHOLD_AUTO_SHUTDOWN_VARIO	= 0x1503,
	PARAM_THRESHOLD_AUTO_SHUTDOWN_UMS	= 0x1504,
	// KalmanParameters
	PARAM_KALMAN_VAR_ZMEAS				= 0x1601,
	PARAM_KALMAN_VAR_ZACCEL				= 0x1602,
	PARAM_KALMAN_VAR_ACCELBIAS			= 0x1603,
	PARAM_KALMAN_SIGMA_P				= 0x1611,
	PARAM_KALMAN_SIGMA_A				= 0x1612,
	// CalibrationData
	PARAM_CALDATA_ACCEL_00				= 0x1701,
	PARAM_CALDATA_ACCEL_01				= 0x1702,
	PARAM_CALDATA_ACCEL_02				= 0x1703,
	PARAM_CALDATA_GYRO					= 0x1710,
	PARAM_CALDATA_GYRO_00				= 0x1711,
	PARAM_CALDATA_GYRO_01				= 0x1712,
	PARAM_CALDATA_GYRO_02				= 0x1713,
	PARAM_CALDATA_MAG					= 0x1720,
	PARAM_CALDATA_MAG_00				= 0x1721,
	PARAM_CALDATA_MAG_01				= 0x1722,
	PARAM_CALDATA_MAG_02				= 0x1723,

	//
	PARAM_EOF							= 0xFFFF
};

struct VarioTone
{
	float 			velocity;

	unsigned short 	freq;
	unsigned short 	period;
	unsigned short 	duty;

};


#endif // __VARIOSETTINGS_H__

